Repository brevia-ai/nuxt-chatbot-layer, pull requests merged in 2025-03, with the labels that each got.

#8 Add chat history UUID to dialog item
  components/ChatZone.vue
Labels: release:patch

#10 Chat Bubble JS script for nuxt-layer
  utils/breviaBubbleScript.js
Labels: release:patch

#11 Integrations with brevia-app
  .playground/app.vue
  components/ChatZone.vue
  server/api/brevia/chat_history.get.ts
  server/api/brevia/collections.get.ts
  server/api/brevia/evaluate.post.ts
  server/utils/api-client.ts
  server/utils/api-error.ts
  utils/breviaBubbleScript.js
Labels: release:minor

#12 fix: real time update to feedback thumbs
  components/ChatZone.vue
Labels: enhancement, release:patch

#13 fix: expose variable to show documents icon on last message
  components/ChatZone.vue
Labels: release:patch
